package com.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CheckinAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckinAllPropertiesEquals(Checkin expected, Checkin actual) {
        assertCheckinAutoGeneratedPropertiesEquals(expected, actual);
        assertCheckinAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckinAllUpdatablePropertiesEquals(Checkin expected, Checkin actual) {
        assertCheckinUpdatableFieldsEquals(expected, actual);
        assertCheckinUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckinAutoGeneratedPropertiesEquals(Checkin expected, Checkin actual) {
        assertThat(actual)
            .as("Verify Checkin auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckinUpdatableFieldsEquals(Checkin expected, Checkin actual) {
        assertThat(actual)
            .as("Verify Checkin relevant properties")
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckinUpdatableRelationshipsEquals(Checkin expected, Checkin actual) {
        assertThat(actual)
            .as("Verify Checkin relationships")
            .satisfies(a -> assertThat(a.getPlayer()).as("check player").isEqualTo(expected.getPlayer()));
    }
}
