package com.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FileDataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileDataAllPropertiesEquals(FileData expected, FileData actual) {
        assertFileDataAutoGeneratedPropertiesEquals(expected, actual);
        assertFileDataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileDataAllUpdatablePropertiesEquals(FileData expected, FileData actual) {
        assertFileDataUpdatableFieldsEquals(expected, actual);
        assertFileDataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileDataAutoGeneratedPropertiesEquals(FileData expected, FileData actual) {
        assertThat(actual)
            .as("Verify FileData auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileDataUpdatableFieldsEquals(FileData expected, FileData actual) {
        assertThat(actual)
            .as("Verify FileData relevant properties")
            .satisfies(a -> assertThat(a.getUid()).as("check uid").isEqualTo(expected.getUid()))
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileDataUpdatableRelationshipsEquals(FileData expected, FileData actual) {
        // empty method
    }
}
