package com.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TournamentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTournamentAllPropertiesEquals(Tournament expected, Tournament actual) {
        assertTournamentAutoGeneratedPropertiesEquals(expected, actual);
        assertTournamentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTournamentAllUpdatablePropertiesEquals(Tournament expected, Tournament actual) {
        assertTournamentUpdatableFieldsEquals(expected, actual);
        assertTournamentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTournamentAutoGeneratedPropertiesEquals(Tournament expected, Tournament actual) {
        assertThat(actual)
            .as("Verify Tournament auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTournamentUpdatableFieldsEquals(Tournament expected, Tournament actual) {
        assertThat(actual)
            .as("Verify Tournament relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getAdditionalInfo()).as("check additionalInfo").isEqualTo(expected.getAdditionalInfo()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStart()).as("check start").isEqualTo(expected.getStart()))
            .satisfies(a -> assertThat(a.getEnds()).as("check ends").isEqualTo(expected.getEnds()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTournamentUpdatableRelationshipsEquals(Tournament expected, Tournament actual) {
        assertThat(actual)
            .as("Verify Tournament relationships")
            .satisfies(a -> assertThat(a.getImage()).as("check image").isEqualTo(expected.getImage()));
    }
}
